<?php
// $Id$

/**
 * @file
 * This is the file description for ${TM_MODULE_TITLE} module.
 *
 * In this more verbose, multi-line description, you can specify what this
 * file does exactly. Make sure to wrap your documentation in column 78 so
 * that the file can be displayed nicely in default-sized consoles.
 */

/**
 * Implements hook_menu().
 */
function ${TM_NEW_FILE_BASENAME}_menu() {
  $items = array();

  // Type '$item ⇥' to create a new menu item.

  return $items;
}

