<?php
// $Id$

/**
 * @file
 * This is the file description.
 *
 * In this more verbose, multi-line description, you can specify what this
 * file does exactly. Make sure to wrap your documentation in column 78 so
 * that the file can be displayed nicely in default-sized consoles.
 */

/**
 * Implementation of hook_menu().
 */
function ${TM_NEW_FILE_BASENAME}_menu($may_cache) {
  $items = array();

  if ($may_cache) {
    // Insert default menu items here.
    // Type '$item' and press tab to create a new menu item.
  }
  else {
    // Insert menu items specific to the current request here.
  }
  return $items;
}

