<?php
/**
 * @file
 * This is the file description for ${TM_MODULE_TITLE} module.
 *
 * In this more verbose, multi-line description, you can specify what this
 * file does exactly. Make sure to wrap your documentation in column 78 so
 * that the file can be displayed nicely in default-sized consoles.
 */

/**
 * Implements hook_menu().
 */
function ${TM_NEW_FILE_BASENAME}_menu($may_cache) {
  $items = array();

  if ($may_cache) {
    // Type '$item ⇥' to create a default menu item here.
  }
  else {
    // Insert menu items specific to the current request here.
  }
  return $items;
}
